global:
  scrape_interval: 2s # Scrape aggressively for real-time dashboard updates during load tests
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'rate-limiter-cluster'
    static_configs:
      - targets:
          - 'rate-limiter-1:3000'
          - 'rate-limiter-2:3000'
          - 'rate-limiter-3:3000'
